name: End to End API Automation

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Suite to run"
        required: true
        type: choice
        default: smoke
        options:
          - workflow

jobs:
  API-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.env }}
    
    env:
      USERID: ${{ secrets.USERID }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run API E2E Tests
        run: mvn test -DsuiteName=${{inputs.suite}}
      - name: Upload Execution log
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log/
