name: API Automation

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Run a suite of tests"
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression

jobs:
  API-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run API Tests
        run: mvn test -DsuiteName=${{inputs.suite}}
      - name: Upload Execution log
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log/
